config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from account import views

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

import account

urlpatterns = [
    # Django authentication
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path('signup/', views.SignUpUser.as_view(), name='signup'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),

    path('3ecret@dminp@nel/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('todo.urls', namespace='todo')),
    path('', include('contact.urls', namespace='contact')),
]

if settings.DEBUG:   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = account.views.error_404

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

todo/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.home, name='home'),
    path('account/current/todo/', views.CurrentToDoList.as_view(), name='current_todo'),
    path('account/complete/todo/', views.CompleteToDoList.as_view(), name='complete_todo'),
    path('account/dashboard/', login_required(TemplateView.as_view(template_name="account/dashboard.html")), name='dashboard'),
    path('account/todo/add/', views.ToDoCreate.as_view(), name='todo_create'),
    path('account/todo/<int:pk>/edit/', views.ToDoUpdate.as_view(), name='todo_update'),
    path('account/todo/<int:pk>/detail/', views.TodoDetail.as_view(), name='todo_detail'),
    path('account/todo/<int:pk>/delete/', views.ToDoDelete.as_view(), name='todo_delete'),
    path('account/todo/<int:pk>/complete/', views.complete_todo, name='completetodo'),
]

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50, required=True, label='نام')
    email = forms.EmailField(required=True, label='ایمیل', help_text='پاسخ شما به این ایمیل ارسال خواهد شد.')
    subject = forms.CharField(max_length=100, required=True, label='موضوع')
    message = forms.CharField(widget=forms.Textarea, required=True, label='پیام شما')

contact/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import ContactForm

# Create your views here.

def contact(request):
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = f"موضوع: {form.cleaned_data['subject']}"
            message = f"اسم: {name}\nپیام: {form.cleaned_data['message']} \n {email}"
            try:
                messages.success(request, 'ایمیل شما با موفقیت ارسال شد. درکوتاه ترین زمان ممکن به شما پاسخ داده خواهد شد.')
                send_mail(subject=subject, message=message, from_email=email, recipient_list=['todomanager04@gmail.com'])
            except BadHeaderError:
                return HttpResponse("ایمیل شما ارسال نشد!")
            return redirect('contact:contact')
    return render(request, 'contact/contact_form.html', {'form': form})

contact/templates/contact/contact_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}تماس باما{% endblock %}

{% block content %}
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-flex align-items-center justify-content-between my-4">
                        <h1 class="h3 mb-0 text-gray-800 mx-auto IranBold">تماس با ما</h1>
                    </div>
                    <div class="col-xl-10 col-lg-7 mx-auto">
                        {% if messages %}
                            <div class="alert alert-primary alert-dismissible fade show text-right shadow rounded" role="alert">
                                {% for message in messages %}
                                    <p{% if message.tags %} class="{{ message.tags }} my-0"{% endif %}><i class="fa fa-check-circle" aria-hidden="true"></i> {{ message }}</p>
                                {% endfor %}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-xl-10 mx-auto text-right">
                        <div class="card shadow mb-4">
                            <!-- Card Header -->
                            <div class="card-header py-3 d-flex bg-primary flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-light IranBold">تماس با ما</h6>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">
                                <form method="post" class="needs-validation" novalidate>
                                    {% csrf_token %}
                                    
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            {% if request.user.is_authenticated %}
                                                <div id="div_id_name" class="form-btn-group-toggle">
                                                    <label for="id_name" class="requiredField">
                                                        نام<span class="asteriskField">*</span>
                                                    </label>
                                                    <input type="text" name="name" maxlength="50" class="textinput textInput form-control" required="" id="id_name" value="{{ request.user.get_full_name }}">
                                                </div>
                                            {% else %}
                                                {{ form.name|as_crispy_field }}
                                            {% endif %}
                                        </div>
                                        <div class="col-md-6">
                                            {% if request.user.is_authenticated %}
                                                <div id="div_id_email" class="form-group">
                                                    <label for="id_email" class=" requiredField">
                                                        ایمیل<span class="asteriskField">*</span>
                                                    </label>
                                                    <div class="">
                                                        <input type="email" name="email" class="emailinput form-control" value="{{ request.user.email }}" required="" id="id_email">
                                                        <small id="hint_id_email" class="form-text text-muted">پاسخ شما به این ایمیل ارسال خواهد شد.</small>
                                                    </div>
                                                </div>
                                            {% else %}
                                                {{ form.email|as_crispy_field }}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-12">
                                            {{ form.subject|as_crispy_field }}
                                        </div>
                                        <div class="col-md-12">
                                            {{ form.message|as_crispy_field }}
                                        </div>
                                    </div>
                                    <button class="btn btn-primary btn-block IranBold" type="submit">ارسال</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
{% endblock %}